### ISSUE TITLE
10.0.14393.2608 x64?

### ISSUE THREAD

**Issue by Tourniquet88** [fre4kyC0de/rdpwrap#1]
Heya,

you wrote "no x64 version". Does this mean it's not compatible with the x64 version? I'm now at 14393.2636 and wanted to try it out, but if it's not for x64 it doesn't make much sense anyway.

**Comment by fre4kyC0de** [comment]
"no x64/x86 version" means, that there is no version of termsrv.dll with that version number (never released by MS).
In short: I don't need to search offsets for that file version as it does not exist.
