### ISSUE TITLE
10.0.14393.2941

### ISSUE THREAD

**Issue by macik** [fre4kyC0de/rdpwrap#10]
Is there any news for 10.0.14393.2941 ?

![image](https://user-images.githubusercontent.com/1009926/57328636-9edeca00-711a-11e9-909e-22fef7fc0acd.png)

**Comment by NinjaInc** [comment]
Having the same issue.. ive tried updating the INI but still not working.. 

Remote Desktop still connects but cant have multiple connections.. any updates to get this working? need it for a few windows 10 sites.

**Comment by NinjaInc** [comment]
**EDIT: This fixed it for me..

[10.0.17763.503]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=77A41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=3E520
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18025
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1ACDC
SLInitFunc.x64=New_CSLQuery_Initialize

bInitialized.x64 =ECAB0
bServerSku.x64 =ECAB4
lMaxUserSessions.x64 =ECAB8
bAppServerAllowed.x64 =ECAC0
bRemoteConnAllowed.x64=ECAC4
bMultimonAllowed.x64 =ECAC8
ulMaxDebugSessions.x64=ECACC
bFUSEnabled.x64 =ECAD0

**Comment by Veon-tech** [comment]
[termsrv_10_0_14393_1737.zip](https://github.com/fre4kyC0de/rdpwrap/files/3386223/termsrv_10_0_14393_1737.zip)
replaced - it works.

**Comment by fre4kyC0de** [comment]
Offsets are online
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.2906.txt
