### ISSUE TITLE
Add how-to to readme

### ISSUE THREAD

**Issue by UksusoFF** [fre4kyC0de/rdpwrap#11]
I have Windows 8 (RDPConf display ver. 6.3.9600.19318).
So open https://raw.githubusercontent.com/fre4kyC0de/rdpwrap/master/6.3.9600.19318.txt 
then Save as... `rdpwrap.ini` near with `RDPWInst.exe`
then `RDPWInst.exe -r`

And still got [not supported]

What's wrong? Where rdpwrap.ini should placed?

**Comment by UksusoFF** [comment]
Found `C:\Program Files\RDP Wrapper\rdpwrap.ini` append data from 6.3.9600.19318.txt and reboot.

Now `RDPConf.exe` show [fully supported]. But still can't connect with second user.

**Comment by fre4kyC0de** [comment]
Take a look at the Readme.

https://github.com/fre4kyC0de/rdpwrap/blob/master/README.md

**Comment by UksusoFF** [comment]
Will be great add search path for rdpwrap.ini at readme.
