### ISSUE TITLE
1903 update - [10.0.18362.53]

### ISSUE THREAD

**Issue by CypherAus** [fre4kyC0de/rdpwrap#12]
This works for 1903 update. BUT you MUST reinstall RDPwrap as well

[10.0.18362.53]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DCC9
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.53-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC

**Comment by NordWest** [comment]
The termservice wont start after insertion this lines into config.  Wrapper version 1.6.2

**Comment by superurbi** [comment]
this addition doen't work for me... I try to connect but I only see a black screen... then an error...

**Comment by CypherAus** [comment]
Refer https://github.com/stascorp/rdpwrap/issues/766


```
[10.0.18362.53]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.53-SLInit]
bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC

```

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/17ca87ad2a35f7cdbe208dad03aced2f9989ca38

I'll include this version and close the issue afterwards

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/b6dc1d90d8c7d4059433693b339803b75105b9cb
