### ISSUE TITLE
New version termserv.dll in 14393.2969

### ISSUE THREAD

**Issue by ristotel** [fre4kyC0de/rdpwrap#14]
updated Win 2016 server few days ago... lost multi rdp...

lets check whats up...

**Comment by s0nic9** [comment]
no problem here with Win2016 14393 updated july 3085 and 3115
dll keep april 2019 update build 2906
remember to keep one blank line at the end of the .ini file and use .ini updated 2018 not the original 2017 .ini (you can check in first section the date of the "base" .ini)

**Comment by fre4kyC0de** [comment]
@s0nic9's answer should've answered your question.
Will close this issue
