### ISSUE TITLE
17763

### ISSUE THREAD

**Issue by Songxwn** [fre4kyC0de/rdpwrap#16]
![image](https://user-images.githubusercontent.com/21145071/62356528-de635980-b543-11e9-85bc-11f8ed3134b4.png)

**Comment by s0nic9** [comment]
try https://github.com/stascorp/rdpwrap/issues/744#issue-432637241

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/17ca87ad2a35f7cdbe208dad03aced2f9989ca38

I'll include this version and close the issue afterwards

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/275e5475c2f4ce279236ec73864ff03b9689e218
