### ISSUE TITLE
Version 6003.20482 problem

### ISSUE THREAD

**Issue by GiuseppeChillemi** [fre4kyC0de/rdpwrap#17]
Hi,
  RDPWrapper show everything green but when the user tries to connect receive an "internal error".

  I have installed in this way:

  Downloaded the latest RDPWrap release 1.62 zip with binaries. 
  Then I have run the installation script.
  Then I have overwritten it with fre4kyC0de 1.62 (all but binaries which are not present in this release). 
  I have then run the update script

  In the c:/program files/rdp*.ini I have appended the offsets found in https://github.com/fre4kyC0de/rdpwrap/blob/master/6.0.6003.20482.txt  (copy/paste of the whole text).

   Rebooted.

   Everything is green.  The system still warns me 2 sessions limit has been reached.

   
   NOTE: Windows Server 2008 R2 SBS here.  Also, after reboot, despite everything is green I get an "internal error" connecting using RDP.

**Comment by s0nic9** [comment]
don't forget the mandatory blank line at the end of the ini

**Comment by fre4kyC0de** [comment]
@s0nic9 should have answered your question
