### ISSUE TITLE
Documentation to create your .ini

### ISSUE THREAD

**Issue by marcussacana** [fre4kyC0de/rdpwrap#18]
Hey, have any documentation to create your own .ini to the win 10?
I managed to found the offsets to that '[10.0.????-SLInit]', but the -SLInit offsets don't make my rpdwrapper recognize the windows as compatible, the non SLInit .ini is very more hard to patch without a example, maybe you can provide a old .dll with a ready .ini to me see what I need do to make my own .ini?
(It's becuse i want use in my insider build)

**Comment by fre4kyC0de** [comment]
> Just add support by adding the offsets from the text file (in this repo) corresponding to the file version "RDPConf" shows at the end of your rdpwrap.ini. Do NOT forget to add a blank line (aka "CR LF") to the end of the ini to prevent RDPWrap from malfunctioning.

Taken from README
