### ISSUE TITLE
Offsets for 6.3.9600.19318 not working

### ISSUE THREAD

**Issue by demobox** [fre4kyC0de/rdpwrap#19]
Thanks for putting together the new offsets, @fre4kyC0de! Unfortunately, on this particular Windows 8.1 Home system (x64), the config for 6.3.9600.19318 does not appear to be working :-(

![image](https://user-images.githubusercontent.com/223702/66705729-6b841500-ed22-11e9-8082-f9dcb1cc2459.png)

I've attached the DLL in case it's somehow different (although I doubt that) - I can only imagine that something else is different, although I've uninstalled and reinstalled RDP Wrapper 1.6.2 a few times to check.

[termsrv-6.3.9600-19318.zip](https://github.com/fre4kyC0de/rdpwrap/files/3720997/termsrv-6.3.9600-19318.zip)

Any thoughts/suggestions would be much appreciated! I should add that, until a recent upgrade, RDP Wrapper was working fine on this system.

**Comment by demobox** [comment]
Attached also the full INI file, just in case

[rdpwrap.zip](https://github.com/fre4kyC0de/rdpwrap/files/3720998/rdpwrap.zip)

**Comment by s0nic9** [comment]
Windows 8.1 home or pro version ?

**Comment by demobox** [comment]
> Windows 8.1 home or pro version ?

Home - "6.3 (build 6900)", according to `winver`

**Comment by s0nic9** [comment]
i havn't yet re-tried home, but it need more than just the dll, the installer install rfxvmt.dll. but yesterday on Win10 home same error as you , i was need to upgrade to pro to work.

**Comment by demobox** [comment]
> i havn't yet re-tried home, but it need more than just the dll, the installer install rfxvmt.dll. but yesterday on Win10 home same error as you

Ah, thanks for the additional detail. By "the installer", do you mean the installer of RDP Wrapper? Or the Windows Update process?

Unfortunately, I'm not able to upgrade the system to Pro, so that fix won't work in my case :-(

**Comment by demobox** [comment]
After a few more attempts, everything now seems to be working! ;-) Not sure which of these steps did it, but what I did included (all as an administrator):

* `RDPWinst -u` to remove RDP Wrapper again
* `RDPWinst -i` to reinstall it
* edit rdpwrap.ini to include the config from https://github.com/fre4kyC0de/rdpwrap/blob/master/6.3.9600.19318.txt
* `RDPWinst -r` to restart necessary services

Now working fine:

![image](https://user-images.githubusercontent.com/223702/66708880-fa466100-ed25-11e9-9425-de6e1f304b82.png)

Side note: I also had to follow the hint in stascorp/rdpwrap#653 to get logging working - I created a directory `...\RDP Wrapper\log` and granted the `NETWORK SERVICE` built-in account write access to it. Now seems to be logging fine:

![image](https://user-images.githubusercontent.com/223702/66708894-60cb7f00-ed26-11e9-809a-1a61d87ee116.png)
