### ISSUE TITLE
Offsets for KB44932472 Win7 32-bit

### ISSUE THREAD

**Issue by obbc** [fre4kyC0de/rdpwrap#2]
Grateful if you could help with this latest security update 2019-04.

Download link for 32-bit http://download.windowsupdate.com/d/msdownload/update/software/secu/2019/04/windows6.1-kb4493472-x86_4315f00d51c820eb1cd13c3af7669aeb80f87d06.msu

& for 64-bit

http://download.windowsupdate.com/c/msdownload/update/software/secu/2019/04/windows6.1-kb4493472-x64_8c89a0b8b74adf3630301e9ff4c071ff56644014.msu

**Comment by fre4kyC0de** [comment]
Should be included in this commit:
https://github.com/fre4kyC0de/rdpwrap/commit/b7f312e35333e17b70ef99407149a1bea811f34e

**Comment by obbc** [comment]
Confirmed working with Win7 32-bit.  Many thanks.
