### ISSUE TITLE
10.0.14393.3383

### ISSUE THREAD

**Issue by promistrio** [fre4kyC0de/rdpwrap#21]
Do you have any ideas?

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.14393.3383.txt

What‘s the problem?
The file worked flawless here on both architectures.

**Comment by pschonmann** [comment]
Not working for me
![obrazek](https://user-images.githubusercontent.com/6333844/71032338-7473d700-2115-11ea-81e0-9dd4ed7f0a05.png)

**Comment by pschonmann** [comment]
Using this version Windows
![obrazek](https://user-images.githubusercontent.com/6333844/71115909-4ead0780-21d3-11ea-828e-81841c843ba1.png)

**Comment by victorhooi** [comment]
I tried this as well on Windows Server 2016, and it didn't work for me either.

Is there any data I can collect that would help narrow down the issue?

**Comment by henrycoule** [comment]
<img width="408" alt="Screen Shot 2020-01-15 at 11 02 44 AM" src="https://user-images.githubusercontent.com/6393255/72454831-41118000-3787-11ea-85cb-6e202a75fb70.png">

It says supported but only two users can actually log in

**Comment by s0nic9** [comment]
@henrycoule don't forget a last blank line at the end of the ini

**Comment by fre4kyC0de** [comment]
Didn't get required infos...
