### ISSUE TITLE
Request for 1909 update. 10.0.18362.267

### ISSUE THREAD

**Issue by expressrussian** [fre4kyC0de/rdpwrap#22]
Hello, 
I will try to publish the original file from win10 1909 enterprise.
Could you develop the patch for it, please?
Thanks 
[termsrv.10.0.18362.267.original.zip](https://github.com/fre4kyC0de/rdpwrap/files/3975349/termsrv.10.0.18362.267.original.zip)

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/b6dc1d90d8c7d4059433693b339803b75105b9cb
