### ISSUE TITLE
RDP settings issue for 6.1.7601.24402

### ISSUE THREAD

**Issue by affinityv** [fre4kyC0de/rdpwrap#25]
https://github.com/fre4kyC0de/rdpwrap/blob/master/6.1.7601.24402.txt

When I added the above to an INI file on a Win7 machine reporting version 6.1.7601.24402, it caused the rdp session to span both screens awkwardly, rather than use both of my different resolution monitors.

I reverted back to an earlier file that didn't have the above text and had to remove and re-install rdpwrap to get back my original config (partially supported, but it works).

This might be a mute point after next weekend though as the old Windows 7 machine is due to be upgraded to Win10 then.

**Comment by s0nic9** [comment]
have you got TeamViewer ?

**Comment by affinityv** [comment]
Definitely no TeamViewer on any machines that I use.

I connect from Linux using xfreerdp, sometimes via ssh tunnel using a Tor hidden service; but this machine is able to be connected to directly (known and trusted IP address at my end).

**Comment by s0nic9** [comment]
have you tried on windows client original rdp client ?

**Comment by affinityv** [comment]
It's okay, once I removed the extra INI file section and reverted to what I had before (as well as uninstall and reinstall RDP Wrapper), all is good; that is, back to normal.

**Comment by affinityv** [comment]
I'm losing Win7 environments quickly (upgrades to Win10).  I wonder if my troubles related to possibly having unix file format instead of dos.  It might be that simple.

**Comment by fre4kyC0de** [comment]
It is;
RDPWrap doesn't like UNIX line ending (LF). If you convert to Windows ones (CRLF) it works.
