### ISSUE TITLE
Windows 10 Version 10.0.18362.267 Offset File

### ISSUE THREAD

**Issue by Essler** [fre4kyC0de/rdpwrap#26]
Requesting offset file for 18362 Win 10 Home (unlike #22 for Windows 10 _Enterprise_.)

- [2020-01 Update for Windows 10 Version 1909 for x64-based Systems (KB4497165)](http://download.windowsupdate.com/c/msdownload/update/software/updt/2020/01/windows10.0-kb4497165-v4-x64_56bf6498dd6757ab61790f40b464c1349c195c11.msu)
- [2020-01 Update for Windows 10 Version 1909 for x86-based Systems (KB4497165)](http://download.windowsupdate.com/d/msdownload/update/software/updt/2020/01/windows10.0-kb4497165-v4-x86_140a67bc9514a8d15f5e813c6f8d3a472037d8e1.msu)

**Comment by Essler** [comment]
@fre4kyC0de, would it be possible to put up a quick doc on how you create the offset files? Just so we can help out.

**Comment by fre4kyC0de** [comment]
I'm doing it the way as described in the original README:
https://github.com/stascorp/rdpwrap/blob/master/README.md

Take a look at "How to find offsets for new termsrv.dll versions".
