### ISSUE TITLE
Request for Windows 10 Home Version 1909 + 18363.657

### ISSUE THREAD

**Issue by cantremember** [fre4kyC0de/rdpwrap#29]
Requesting offset file for Windows 10 Home Version 1909 + 18363.657

- [KB4532693 (OS Builds 18362.657 and 18363.657)](https://support.microsoft.com/en-us/help/4532693/windows-10-update-kb4532693)
- [2020-02 Cumulative Update for Windows 10 Version 1909 for x86-based Systems (KB4532693)](http://download.windowsupdate.com/d/msdownload/update/software/secu/2020/02/windows10.0-kb4532693-x86_149a95ca991206cf8df78d172250c55fec5a4fad.msu)
- [2020-02 Cumulative Update for Windows 10 Version 1909 for x64-based Systems (KB4532693)](http://download.windowsupdate.com/d/msdownload/update/software/secu/2020/02/windows10.0-kb4532693-x64_e22f60a077a0ec5896266a18cc3daf26bfc29e16.msu)

^^^ i hope that's the set of information you need 🙏

**Comment by cantremember** [comment]
@fre4kyC0de, would it be possible to put up a quick doc on how you create the offset files? Just so we can help out.

**Comment by fre4kyC0de** [comment]
I'm doing it the way as described in the original README:
https://github.com/stascorp/rdpwrap/blob/master/README.md

Take a look at "How to find offsets for new termsrv.dll versions".

Currently I cannot create offsets for 17763 and newer as my testing environment does not support it; and I didn't have the time to add proper support for these versions yet. I found a quite hacky way to get the offsets, but I don't want to use it for different reasons...

**Comment by cantremember** [comment]
thank you for the response -- just so that I understand

> I'm doing it the way as described in the original README:

> I found a quite hacky way to get the offsets

"hacky" in a way that is *different* from the original README -- i'm guessing under [How to find offsets for new termsrv.dll versions](http://www.youtube.com/watch?v=FiD86tmRBtk)?

as in, did you effectively 'branch' your current procedure off of the one that you last documented?  is it reasonable to believe that the README's documented procedure will still produce reasonable results?  i'll be happy to give it a shot, @fre4kyC0de , if it's still reliable

**Comment by fre4kyC0de** [comment]
Some offsets moved between the versionsn(starting with 17134), that‘s correct, but I‘m talking about getting the files...
The offsets are determined on a RasPi using a script, which uses cdb to create the files. This doesn‘t work anymore as there are just delta-patches in the updates. And setting up and updating 4 virtual computers (as slipstreaming isn‘t reliable since somewhere in 2015/2016 anymore) takes a lot of time.
To circumvent this, I found a hacky way, but it is not the ideal way for different reasons.

**Comment by cantremember** [comment]
new offsets & a `rdpwrap.ini` for 10.0.18363.657 (also 10.0.18362.657) can be found in [](https://github.com/stascorp/rdpwrap/issues/988)
