### ISSUE TITLE
Windows 10 1809 termsvr.dll version 10.0.17763.437

### ISSUE THREAD

**Issue by Kangaa87** [fre4kyC0de/rdpwrap#3]
Great to see someone keeping RDPWrap going. Thanks for the work you do.

There is a new termsvr.dll version for Windows 10 1809. It is part of the April monthly security update KB4493509. Download links here: http://www.catalog.update.microsoft.com/Search.aspx?q=KB4493509

New termsvr.dll version is 10.0.17763.437 after applying this update.

Some offsets were posted in thread on stascorp repo, but they are incomplete/wrong. For example, single session per user does not work. Threads here:
https://github.com/stascorp/rdpwrap/issues/720
 and here:
 https://github.com/stascorp/rdpwrap/issues/729

**Comment by fre4kyC0de** [comment]
Currently I cannot extract the files for 1809 and higher automatically, that‘s why I did not support it yet. Could change this weekend, if the last tests of something new pass.

**Comment by Kangaa87** [comment]
Sounds promising, I'll keep my fingers crossed.

Just out of curiosity, is something encrypted now? .cab files or the termsvr.dll itself ?

**Comment by jaggeri** [comment]
Please do fix Windows 10 ver1809 !

Meanwhile, I will see if I can uninstall and revert back to ver 1803.

**Comment by fre4kyC0de** [comment]
@Kangaa87 
In updates for Windows Vista / Server 2008 up to Windows 10 1803 (17134) the updated files were packed somewhere inside the MSU/CAB. Starting with Windows 10 1809 (17763) /  Server 2019 only a delta of the new file to the last revision and to the original file is inside the MSU/CAB.

@jaggeri 
I'm doing the reversing on Linux / Raspberry Pi, which isn't able to parse the new update format yet. So I currently cannot get termsrv.dll in newer revisions than the original one. I'm currently working on a parser, but it's not working yet.

**Comment by stwubby** [comment]
If only these corpse erations would spend as much time on making their products better and less on trying to lock you out they would be so much farther ahead and cheaper probably. Why don't they get that?

**Comment by fre4kyC0de** [comment]
MS did that to decrease the size of the cumulative updates (1,5GB before, 150MB now), which is a pretty good decision. But exactly that decision currently makes it impossible to get the updated files without setting up a virtual machine, installing the next rollup and copying the file. Doing so for every future Windows 10 build in x86 and x64 will take ages just to get the files. I do not have that much time.
I‘ll just do 1809 and newer offsets, if I find a way to extract the newer revisions from the updates without having to install them. My current attempt successfully failed.

**Comment by Kangaa87** [comment]
I have to say, if I was stuck with a rasbpi as my daily driver, I'd have to think seriously about my choice of lifestyle/career.   ;-)

Mad props to you for trying though. Successful failures are always a good learning opportunity.

(I'd happily offer to send you any files you need and pinky swear they are clean, but since I'm some random person you don't know then there's no reason to trust me).

**Comment by fre4kyC0de** [comment]
The RasPi is not my daily driver, but it‘s used for reversing as I don‘t want to break my main computer (I did that a lot of times while testing patches and modifications and fixing it at night after work isn‘t my favourite task)...

I know, that it‘s pretty easy to get the files (install in VM and copy them), but that is no solution for a long time (thinking about all LTSC builds and how much storage and time that would take to maintain). There has to be a proper solution, which works with just the RTM termsrv.dll and the update.

For now I‘ll set up the VMs and get the files and maybe find out, how to extract them from the updates (ProcMon is your friend).

**Comment by fre4kyC0de** [comment]
If someone has a workong parser for the new update format, please let me know.

**Comment by fre4kyC0de** [comment]
#7
