### ISSUE TITLE
Request for Windows 10 Pro  Version:1909  OS Build:18363.657

### ISSUE THREAD

**Issue by SJLBoulder** [fre4kyC0de/rdpwrap#30]
I believe the offset change occurred with Quality Update:
2020-02 Cumulative Update for Windows 10 Version 1909 (KB4532693)

Thanks.

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/17ca87ad2a35f7cdbe208dad03aced2f9989ca38
