### ISSUE TITLE
solicitud 10.018362.657

### ISSUE THREAD

**Issue by johncharly26** [fre4kyC0de/rdpwrap#31]
solicitud 10.0.18362.657  ayuda ´por favor

**Comment by streunerlein** [comment]
https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini works good

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/b6dc1d90d8c7d4059433693b339803b75105b9cb
