### ISSUE TITLE
10.0.18362.836

### ISSUE THREAD

**Issue by ezrapedersen** [fre4kyC0de/rdpwrap#36]

**Comment by ilshatkin2020** [comment]
Does anyone have one wrapper.ini to 10.0.18362.836?

**Comment by ilshatkin2020** [comment]
Windows was updated and rpd stopped working

**Comment by Int32Overflow** [comment]
@ezrapedersen Do you have a correct wrapper.ini for 10.0.18362.836 or why why did you close the issue?

**Comment by ilshatkin2020** [comment]
I deleted the last update and everything worked, 
May 12, 2020—KB4556799 (OS Builds 18362.836 and 18363.836)

  
>Среда, 13 мая 2020, 11:46 +03:00 от Int32Overflow <notifications@github.com>:
> 
> 
>@ezrapedersen Do you have a correct wrapper.ini for 10.0.18362.836 or why why did you close the issue?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Ильшат сайфуллин
