### ISSUE TITLE
18363.836

### ISSUE THREAD

**Issue by acehigh30** [fre4kyC0de/rdpwrap#38]
Hello, looking for 18363.836 the 18362.836 does not work.  I tried modifying the .ini to reflect 18363.836 but my skills are lacking.  Thanks.

**Comment by fragtion** [comment]
You might have better luck modifying another 18363.x than going all the way back to 18362.836 :-
Here is 18363.476 if you want to give that a go...otherwise I hope someone else can help you.
```
[10.0.18363.476]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18363.476-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC
```

**Comment by acehigh30** [comment]
Yep your right, thanks for the advice.  I'm just starting to dip my toe into this stuff.  I've been trying to use what you provided but no luck yet.  No idea where to go if it's not posted here now that stascorp is offline.

**Comment by ilshatkin2020** [comment]
I deleted the last update and everything worked, 
May 12, 2020—KB4556799 (OS Builds 18362.836 and 18363.836)

**Comment by sia380** [comment]
Working RDPWrap.ini for 18363.836:

[rdpwrap v18363.836.zip](https://github.com/fre4kyC0de/rdpwrap/files/4626244/rdpwrap.v18363.836.zip)

**Comment by ilshatkin2020** [comment]
Oh, Thank you very much)))

  
>Четверг, 14 мая 2020, 8:40 +03:00 от sia380 <notifications@github.com>:
> 
> 
>Working RDPWrap.ini for 18363.836:
>rdpwrap v18363.836.zip
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Ильшат сайфуллин

**Comment by TGeRi** [comment]
Thanks!

**Comment by yorchwa** [comment]
Does anybody know if this new rdwrap.ini work for w10. 32 bits (X86). Thanks

**Comment by datahostuk** [comment]
Thank you!

**Comment by KifReact** [comment]
> Working RDPWrap.ini for 18363.836:
> 
> [rdpwrap v18363.836.zip](https://github.com/fre4kyC0de/rdpwrap/files/4626244/rdpwrap.v18363.836.zip)

thanks, it worked for me

**Comment by acehigh30** [comment]
I'm still getting version 10.0.18362.832 and not listening when running RDPConf.exe.  I've rebooted multiple times, ran elevated cmd RDPWinst -r replaced the entire file, cut and pasted the code and it still won't take.

**Comment by TGeRi** [comment]
Are you sure that you have an EMPTY LINE at the end of the ini?

**Comment by allisongsa** [comment]
Hello,

the x.64 version of  10.0.18363.836 is working fine for me, but I need the x86 version also, does anyone have this? Many thanks...

**Comment by acehigh30** [comment]
There is, I just double-checked and even added two empty lines then tried no empty lines.  I'll get it figured out.

**Comment by acehigh30** [comment]
> Are you sure that you have an EMPTY LINE at the end of the ini?

Finally figured out out.  I had an old rdp wrapper in my (x86) files that I kept dropping the .ini in.  Duh!

**Comment by sia380** [comment]
> Hello,
> 
> the x.64 version of 10.0.18363.836 is working fine for me, but I need the x86 version also, does anyone have this? Many thanks...

Are you able to test if this works on x86? Thanks!

[rdpwrap x86 v18363.836.zip.zip](https://github.com/fre4kyC0de/rdpwrap/files/4629590/rdpwrap.x86.v18363.836.zip.zip)

**Comment by yorchwa** [comment]
Hi. Not working for me in X86. Thanks.

**Comment by allisongsa** [comment]
Just tried the x86 version and no joy, Remote Desktop Services starts and then stops and won’t “listen”...

**Comment by dcbasso** [comment]
I cant make work here.
I use the ini file here and nothing change.

**Comment by ilshatkin2020** [comment]
You need to restart the remote desktop service

**Comment by dcbasso** [comment]
I reboot the system, and nothing change.

**Comment by ilshatkin2020** [comment]
windows 
64 bit?

**Comment by dcbasso** [comment]
Correct!

**Comment by ilshatkin2020** [comment]
C:\Program Files\RDP Wrapper  ?

**Comment by ilshatkin2020** [comment]
the folder has write permissions

**Comment by dcbasso** [comment]
have write permissions. Correct the correct the folder.
I uninstall the update and I still with problems.

**Comment by dcbasso** [comment]
I check the file in "C:\Program Files\RDP Wrapper" and appears "404 not found" in the file.

**Comment by a-lascu** [comment]
I also need the x86 version. Can anyone help?

**Comment by s0nic9** [comment]
PLEASE don't mix windows version and version reported by rdpconf.exe (=termsrv.dll version)
there is not 18363.836 version reported by rdpconf.exe (=termsrv.dll version)
Only 18362.836 sections are needed for both Windows 10 1903 and 1909 main version.

**Comment by sia380** [comment]
> PLEASE don't mix windows version and version reported by rdpconf.exe (=termsrv.dll version)
> there is not 18363.836 version reported by rdpconf.exe (=termsrv.dll version)
> Only 18362.836 sections are needed for both Windows 10 1903 and 1909 main version.

You will need both 18362.836 and 18363.836 entries in the .ini file for it to work on a 1836**3**.836 Windows OS. This is because the termsrv.dll version still remains as 1836**2**.836.

**Comment by ilshatkin2020** [comment]
RDPWInst ,then  install  ,then rdpwrap.v18363.836 to extract folder, replace rdpwrap.ini file from folder
to C:\Program Files\RDP Wrapper and reboot  remote desktop service

**Comment by yorchwa** [comment]
In my case with X86 appears as fully supported but the service is intermittently stopped/started and does not work.
![image](https://user-images.githubusercontent.com/59339954/82022968-cf423800-968d-11ea-9225-17204c8d339c.png)

**Comment by TGeRi** [comment]
Upload your current ini to pastebin and post a link of it here

**Comment by yorchwa** [comment]
This is the ini file.
[rdpwrap.x86.v18363.836.zip.zip](https://github.com/fre4kyC0de/rdpwrap/files/4632891/rdpwrap.x86.v18363.836.zip.zip)

**Comment by allisongsa** [comment]
Just tried x86 version again and I have the same symptoms, Remote Desktop Services just keeps starting and stopping then fails.

**Comment by allisongsa** [comment]
Can confirm that you only need the entries for 10.0.18362.836 (x64) to work with the **18363** operating system, that is what I am using.

**Comment by allisongsa** [comment]
> > PLEASE don't mix windows version and version reported by rdpconf.exe (=termsrv.dll version)
> > there is not 18363.836 version reported by rdpconf.exe (=termsrv.dll version)
> > Only 18362.836 sections are needed for both Windows 10 1903 and 1909 main version.
> 
> You will need both 18362.836 and 18363.836 entries in the .ini file for it to work on a 1836**3**.836 Windows OS. This is because the termsrv.dll version still remains as 1836**2**.836.

**Comment by gazousg** [comment]
hi, have same probleme here 
LISTENING / NOT SUPPORTED
windows 10 18363.836
did everything.. restart .....

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/d98a85f267b68ef900a85b7ebdc2ab583e54f110
