### ISSUE TITLE
Unable to get 10.0.18362.836 working

### ISSUE THREAD

**Issue by LoYungSum** [fre4kyC0de/rdpwrap#39]
I know in issue #37 . There is a new ini file for this version. But after I use the ini file, the remote desktop service will be stopped when I run the RDPConf.exe, but if I go to the Windows Settings App and Remote Desktop Configuration, it said the service is running.

When I try to remote desktop it to the computer, it will said it was unable to connect to the computer and tell me to check if the computer is on and running. I tried reinstalling the rdp wrapper, but still no luck

FYI, if you reinstall the rdp wrapper, the ini file will be blank (or "404 Error"), maybe because the main repo is shutdown by Microsoft, so I must apply a whole new ini file to the system.

**Comment by trxmaster** [comment]
https://gofile.io/d/kdlPTR 
instal rdpwrap C:\Program Files\RDP Wrapper next just paste download file inside folder

**Comment by LoYungSum** [comment]
Thanks. It's working

**Comment by FMYY** [comment]
Thank you so much。
Solved the problem that cannot be used after kb4556799 update
The source github is no longer available，To avoid this happening again，Do you have any alternative contact information.If the price is right, I would like to be a long-term paying user

**Comment by CaCTuCaTu4ECKuu** [comment]
Tnx, solve issue for me too.
Definitely should be fixed in future release

**Comment by allisongsa** [comment]
Can confirm that you only need the entries for 10.0.18362.836 (x64) to work with the **18363** operating system, that is what I am using.

**Comment by amuggia** [comment]
Dont work for me, unsupported.

**Comment by fre4kyC0de** [comment]
https://github.com/fre4kyC0de/rdpwrap/commit/d98a85f267b68ef900a85b7ebdc2ab583e54f110
