### ISSUE TITLE
10.0.10240.18186

### ISSUE THREAD

**Issue by sevakgrig** [fre4kyC0de/rdpwrap#5]
Hello fre4kyC0den.
The configuration for your link (https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.10240.18186.txt) did not work for me.

![wrapper](https://user-images.githubusercontent.com/46564800/56091920-d06ac980-5ebd-11e9-93b8-1530c052446d.png)

A complete reinstall of the wrapper, restarting the computer did not help either. Can you help me solve this problem?

**Comment by fre4kyC0de** [comment]
In the initial version was a copy-paste error, just to check: Could you post the „DefPolicyOffset.x64„ offset you use?

**Comment by sevakgrig** [comment]
i am use this config :

[10.0.10240.18186]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=A8048
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=96A41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=32B15
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=17264
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=2F699
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=EDC5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=3FA58
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=249D0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.10240.18186-SLInit]
bFUSEnabled.x86       =C4F88
lMaxUserSessions.x86  =C4F8C
bAppServerAllowed.x86 =C4F90
bInitialized.x86      =C4F94
bMultimonAllowed.x86  =C4F98
bServerSku.x86        =C4F9C
ulMaxDebugSessions.x86=C4FA0
bRemoteConnAllowed.x86=C4FA4

lMaxUserSessions.x64  =F23B0
bAppServerAllowed.x64 =F23B4
bServerSku.x64        =F23B8
bFUSEnabled.x64       =F3460
bInitialized.x64      =F3464
bMultimonAllowed.x64  =F3468
ulMaxDebugSessions.x64=F346C
bRemoteConnAllowed.x64=F3470

**Comment by fre4kyC0de** [comment]
32bit or 64bit?

I already got success reports for that version.

**Comment by sevakgrig** [comment]
Windows 10 Enterprise 2015 LTSB (x64)

**Comment by fre4kyC0de** [comment]
Did you add a blank line at the end of rdpwrap.ini?

**Comment by sevakgrig** [comment]
once again reinstalled wrapper and this time it worked.
Thanks!
