### ISSUE TITLE
Entire rdpwrap.ini

### ISSUE THREAD

**Issue by joebrug** [fre4kyC0de/rdpwrap#6]
hey @fre4kyC0de .. curious why not just host a complete rdpwrap.ini with StasM + your offsets? users are obviously screwing up the copy/paste, etc. Figured it'd be easier to just say "download this rdpwrap.ini and replace your current one, reboot"

**Comment by fre4kyC0de** [comment]
Maybe I‘ll do in the future, but I won‘t promise to do so.

It‘s easier for me to do it in this format.
