### ISSUE TITLE
10.0.14393.2906.txt

### ISSUE THREAD

**Issue by jjwhite77** [fre4kyC0de/rdpwrap#9]
10.0.14393.2906.txt is not working.  Everything turns green making you think all is good but this patch is not working.  
Please Help 

Thank You

**Comment by henrycoule** [comment]
The same thing is happening to me too

**Comment by benkisley** [comment]
Same thing is happening to me

**Comment by 424778940z** [comment]
terminal service will fail to start when this applied after reboot.

**Comment by mayerwin** [comment]
I had the exact same issue, but was able to fix it and get RDP Wrapper to work smoothly by just adding a space (blank line) at the end of the ini file (then restart the computer)! I hope it helps.
